// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Bookmark struct {
	ID        uuid.UUID
	Url       string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type BookmarkHasComment struct {
	BookmarkID uuid.NullUUID
	TagID      uuid.NullUUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type BookmarkHasTag struct {
	BookmarkID uuid.NullUUID
	TagID      uuid.NullUUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Comment struct {
	ID        uuid.NullUUID
	Comment   string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Tag struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
