// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Bookmark struct {
	ID          uuid.UUID
	Url         string
	Title       string
	Description string
	Thumbnail   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type BookmarkHasTag struct {
	ID         uuid.UUID
	BookmarkID uuid.UUID
	TagID      uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Comment struct {
	ID         uuid.UUID
	BookmarkID uuid.UUID
	Comment    string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Tag struct {
	ID        uuid.UUID
	Name      string
	Color     string
	CreatedAt time.Time
	UpdatedAt time.Time
}
